# Generated by Django 4.0.6 on 2022-07-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
