# Generated by Django 4.0.6 on 2022-08-02 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cape', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
