# Generated by Django 4.0.6 on 2022-08-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cape', '0005_post_is_archieved_alter_profile_organization_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('can_check_archived', 'can checked archived'),)},
        ),
    ]
