# Generated by Django 4.0.6 on 2022-08-04 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cape', '0007_alter_comment_managers_comment_is_archived'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='comment',
            managers=[
            ],
        ),
    ]
