# Generated by Django 4.0.6 on 2022-08-04 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cape', '0008_alter_comment_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_archieved',
            new_name='is_archived',
        ),
    ]
